function changeFishPage() {
    var buttonFish = document.querySelector('#button-container');
    buttonFish.innerHTML = '<div class="row"><div class="first-fish-bl"><div class="type">Dried</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/korushka.jpg"></div> <div class="text">European smelt</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/lyash.png"></div> <div class="text">Carp bream </div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/plotva.jpg"></div><div class="text">Roach</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/okyn.jpg"></div><div class="text">Perch</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/buchok.png"></div><div class="text">Goby</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/hys.jpg"></div> <div class="text">White bream </div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Smoked</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/salaka.jpg"></div> <div class="text">Baltic herring </div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/sayra.jpg"></div> <div class="text">Saury</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/skymbria.png"></div><div class="text">Mackerel</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/moyva.jpg"></div><div class="text">Capelin</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/oselede.jpeg"></div><div class="text">Herring</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/hrebet.png"></div> <div class="text">Salmon frames </div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Salted </div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/oselede.jpg"></div> <div class="text">Herring</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/salaka.jpg"></div> <div class="text">Baltic herring</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/forel.jpg"></div><div class="text">Trout </div></div> </div></div><div class="row"><div class="first-fish-bl"><div class="type">Seafood</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/salat.jpg"></div> <div class="text">Seaweed</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/midii.jpg"></div> <div class="text">Mussels</div> </div> </div></div>';
    document.getElementById('home-button').style.display = 'block';
}


function changeMeatPage() {
    var buttonMeat = document.querySelector('#button-container');
    buttonMeat.innerHTML = '<div class="block"><p class="type">Chicken parts, by-products </p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/bedra.jpg"></div><div class="text">Thigh </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/homika.jpg"></div><div class="text">Drumsticks </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/spynka.jpg"></div><div class="text">BacksS</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/kryl.jpg"></div><div class="text">Wings </div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/file.jpeg"></div><div class="text">Breast filet </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/ser.jpg"></div><div class="text">Hearts</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/shlynok.jpg"></div><div class="text">Gizzards </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/farsh.png"></div><div class="text">MDM</div></div></div></div></div><div class="block"><p class="type">Pork  parts, by-products</p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/vurizka.jpg"></div><div class="text">Trimmings </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/pechinka.jpg"></div><div class="text">Liver</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/kin.jpeg"></div><div class="text">Legs</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/farsh.png"></div><div class="text">MDM</div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shuya.jpg"></div><div class="text">Neck</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/nurku.jpeg"></div><div class="text">Kidneys </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/leg.jpg"></div><div class="text">Lights </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shlynok.png"></div><div class="text">Gizzards </div></div></div></div>'
    document.getElementById('home-button').style.display = 'block'; value='Back';
}

function homePage() {
    var homeButton = document.querySelector('#button-container');
    homeButton.innerHTML = ' <input class="product-button button-fish" type="submit" value="Fish" onclick="changeFishPage()"/><input class="product-button button-meat" type="submit" value="Meat" onclick="changeMeatPage()"/>'
    document.getElementById('home-button').style.display = 'none';
}
