function changeFishPage() {
    var buttonFish = document.querySelector('#button-container');
    buttonFish.innerHTML = '<div class="row"><div class="first-fish-bl"><div class="type">В’ялена</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/korushka.jpg"></div> <div class="text">Корюшка</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/lyash.png"></div> <div class="text">Лящ</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/plotva.jpg"></div><div class="text">Плотва</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/okyn.jpg"></div><div class="text">Окунь</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/buchok.png"></div><div class="text">Бичок</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/hys.jpg"></div> <div class="text">Густера</div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Копчена</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/salaka.jpg"></div> <div class="text">Салака</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/sayra.jpg"></div> <div class="text">Сайра</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/skymbria.png"></div><div class="text">Скумбрія</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/moyva.jpg"></div><div class="text">Мойва</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/oselede.jpeg"></div><div class="text">Оселедець</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/hrebet.png"></div> <div class="text">Хребет лосося</div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Солена</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/oselede.jpg"></div> <div class="text">Оселедець</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/salaka.jpg"></div> <div class="text">Салака</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/forel.jpg"></div><div class="text">Форель</div></div> </div></div><div class="row"><div class="first-fish-bl"><div class="type">Морепродукти</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/salat.jpg"></div> <div class="text">Морська капуста</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/midii.jpg"></div> <div class="text">Мідії</div></div></div></div></div>';
    document.getElementById('home-button').style.display = 'block';
}


function changeMeatPage() {
    var buttonMeat = document.querySelector('#button-container');
    buttonMeat.innerHTML = '<div class="block"><p class="type">Курячі частини, субпродукти та продукти механічної обробки</p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/bedra.jpg"></div><div class="text">Бедра</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/homika.jpg"></div><div class="text">Гомілки</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/spynka.jpg"></div><div class="text">Спинки</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/kryl.jpg"></div><div class="text">Крильця</div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/file.jpeg"></div><div class="text">Філе</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/ser.jpg"></div><div class="text">Серця</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/shlynok.jpg"></div><div class="text">Шлунки</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/farsh.png"></div><div class="text">Фарш</div></div></div></div></div><div class="block"><p class="type">Свинні частини, субпродукти та продукти механічної обробки</p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/vurizka.jpg"></div><div class="text">Вирізка</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/pechinka.jpg"></div><div class="text">Печінка</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/kin.jpeg"></div><div class="text">Кінцівки</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/farsh.png"></div><div class="text">Фарш</div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shuya.jpg"></div><div class="text">Шия</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/nurku.jpeg"></div><div class="text">Нирки</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/leg.jpg"></div><div class="text">Легені</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shlynok.png"></div><div class="text">Шлунки</div></div></div></div>'
    document.getElementById('home-button').style.display = 'block';
}

function homePage() {
    var homeButton = document.querySelector('#button-container');
    homeButton.innerHTML = ' <input class="product-button button-fish" type="submit" value="Риба" onclick="changeFishPage()"/><input class="product-button button-meat" type="submit" value="М’ясо" onclick="changeMeatPage()"/>'
    document.getElementById('home-button').style.display = 'none';
}
