function changeFishPage() {
    var buttonFish = document.querySelector('#button-container');
    buttonFish.innerHTML = '<div class="row"><div class="first-fish-bl"><div class="type">Suszona</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/korushka.jpg"></div> <div class="text">Koruszka</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/lyash.png"></div> <div class="text">Leszcz</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/вялена/plotva.jpg"></div><div class="text">Płoć</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/okyn.jpg"></div><div class="text">Okoń</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/buchok.png"></div><div class="text">Byczek </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/вялена/hys.jpg"></div> <div class="text">Hustela</div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Wędzona</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/salaka.jpg"></div> <div class="text">Szprot</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/sayra.jpg"></div> <div class="text">Saira</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/копчена/skymbria.png"></div><div class="text">Makrela</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/moyva.jpg"></div><div class="text">Kapelan</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/oselede.jpeg"></div><div class="text">Śledź</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/fish img/копчена/hrebet.png"></div> <div class="text">Łosoś grzbiety </div></div></div></div><div class="row"><div class="first-fish-bl"><div class="type">Słona</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/oselede.jpg"></div> <div class="text">Śledź</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/salaka.jpg"></div> <div class="text">Szprot</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/солені/forel.jpg"></div><div class="text">Pstrąg</div></div> </div></div><div class="row"><div class="first-fish-bl"><div class="type">Owoce morza</div><div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/salat.jpg"></div> <div class="text"> Modrak morski</div> </div> <div class="fish-block"> <div class="image"><img class="photo" src="./new img/fish img/морепродукти/midii.jpg"></div> <div class="text">Małże</div> </div> </div></div>';
    document.getElementById('home-button').style.display = 'block'; 
}


function changeMeatPage() {
    var buttonMeat = document.querySelector('#button-container');
    buttonMeat.innerHTML = '<div class="block"><p class="type">Części i producty uboczne drobiowe </p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/bedra.jpg"></div><div class="text">Biodro</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/homika.jpg"></div><div class="text">Goleń</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/spynka.jpg"></div><div class="text">Oparcie </div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/kryl.jpg"></div><div class="text">Skrzydełka </div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/file.jpeg"></div><div class="text">Filety</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/ser.jpg"></div><div class="text">Serce</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/shlynok.jpg"></div><div class="text">Żołądek</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/cheken/farsh.png"></div><div class="text">Farsz</div></div></div></div></div><div class="block"><p class="type">Wieprowina, producty uboczne</p><div class="obh"><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/vurizka.jpg"></div><div class="text">Polędwica</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/pechinka.jpg"></div><div class="text">Wątroba</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/kin.jpeg"></div><div class="text">Końcówki</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/farsh.png"></div><div class="text">Farsz</div></div></div><div class="first-fish-bl"><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shuya.jpg"></div><div class="text">Szyja</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/nurku.jpeg"></div><div class="text">Nerka</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/leg.jpg"></div><div class="text">Płuc</div></div><div class="fish-block"><div class="image"><img class="photo" src="./new img/meat/pig/shlynok.png"></div><div class="text">Członki</div></div></div></div>'
    document.getElementById('home-button').style.display = 'block'; 
}

function homePage() {
    var homeButton = document.querySelector('#button-container');
    homeButton.innerHTML = ' <input class="product-button button-fish" type="submit" value="Ryba" onclick="changeFishPage()"/><input class="product-button button-meat" type="submit" value="Мięso" onclick="changeMeatPage()"/>'
    document.getElementById('home-button').style.display = 'none';
}
